apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: todo
  labels:
    app: todo-api
spec:
  selector:
    app: todo-api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8082         # ClusterIP port (internal)
      targetPort: 8082   # Container port
      nodePort: 30082    # Externally accessible on localhost:30082
